version: "3"
services:
  bb:
    image: mongo:3-xenial
    container_name: mongo-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db:rw

  bbmanager:
    image: mongo-express
    links:
      - bb:db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  # mape:
  #   image: mape_system:latest
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./log:/mape/log
  #   links:
  #     - bb:mongodb
  #   network_mode: "host"
    # ports: 
      # - 5522:5522
  web:
    build: ./picalculator/

  proxy:
    build: proxy
    ports: 
      - 8222:8222
