apiVersion: 1

datasources:
  - name: prometheusdata
    type: Prometheus
    access: direct
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true