{
 "title": "IoT Workload Generator",
 "description": "visualizing iot workload generator metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(iotwg_web_response_time_count[$__interval])",
     "legendFormat": "successfull"
    },
    {
     "expr": "rate(iotwg_web_failed_requests[$__interval])",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Sensor Count",
   "type": "graph",
   "description": "Number of simultaneous sensors sending requests to the webserver",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "iotwg_sensor_count" }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "description": "average response time for successful requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(iotwg_web_response_time_sum[$__interval])/rate(iotwg_web_response_time_count[$__interval])"
    }
   ]
  },
  {
   "title": "Simulator Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "iotwg_simulator_up" }
   ]
  }
 ]
}