{
 "title": "MAPE Experiment dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service name", "query": "${VAR_SERVICE}" }
  ]
 },
 "panels": [
  {
   "title": "Response Time vs Arrival Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(iotwg_web_response_time_sum[$__interval])/rate(iotwg_web_response_time_count[$__interval])",
     "legendFormat": "response time"
    },
    {
     "expr": "rate(iotwg_web_response_time_count[$__interval])",
     "legendFormat": "arrival rate"
    }
   ]
  },
  {
   "title": "Cpu utilization vs Containers (#)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Cpu Utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1m])) by(container_label_com_docker_compose_service) /\r\nsum(container_spec_cpu_quota/container_spec_cpu_period) by (container_label_com_docker_compose_service)",
     "legendFormat": "cpu utilization"
    },
    {
     "expr": "count(container_last_seen{name=~\".+\",container_label_com_docker_compose_service=\"web\"})",
     "legendFormat": "containers (#)"
    }
   ]
  },
  {
   "title": "Service Price vs Number of ads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Ads / request (#)" }
   ],
   "targets": [
    {
     "expr": "mape_economic_analysis_service_price",
     "legendFormat": "service price"
    },
    {
     "expr": "mape_economic_analysis_ads_count",
     "legendFormat": "ads"
    }
   ]
  },
  {
   "title": "Profits vs user satisfaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Profit ($/ second)" }
   ],
   "targets": [
    {
     "expr": "mape_economic_analysis_service_profit",
     "legendFormat": "service profit"
    },
    {
     "expr": "mape_economic_analysis_app_profit",
     "legendFormat": "client profit"
    },
    {
     "expr": "mape_economic_analysis_user_satisfaction",
     "legendFormat": "user satisfaction"
    }
   ]
  }
 ]
}